### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by alissonlucrecio** [b2tradingclub/profitchart-estrategias#1]
Olá Danilo,

Queria falar como você sobre essa função. Você poderia me passar seu contato? Obrigado.

**Comment by jozephbrasil** [comment]
Sobre qual função?

**Comment by jozephbrasil** [comment]
Você pode conversar com ele por aqui. Sua dúvida pode ser a de outros também.

**Comment by EduardoGubert** [comment]
Ola boa tarde, qual linguagem vc se baseá para fazer esses códigos do profit

**Comment by jozephbrasil** [comment]
> Ola boa tarde, qual linguagem vc se baseá para fazer esses códigos do profit ?

Você pode obter mais informações em https://www.facebook.com/groups/estrategiasbacktestsprofitchart/permalink/2159725090730131/?comment_tracking=%7B%22tn%22%3A%22O%22%7D

**Comment by MarcosTrader** [comment]
Oi Jozeph Brazil,

Não sou programador, mas opero no profit.

Como insiro estes indicadores de fibo e formato às minhas estratégias no proft?

**Comment by jozephbrasil** [comment]
@MarcosTrader você precisa usar o editor de estratégias. Entra no grupo https://www.facebook.com/groups/estrategiasbacktestsprofitchart/ que fica mais fácil ajudar por lá.
