### ISSUE TITLE
Fab4 - Oliver Velez

### ISSUE THREAD

**Issue by luiztosi** [b2tradingclub/profitchart-estrategias#10]
Pessoal, estou tentando criar um screening no profitchart, alguem já mexeu com isso?

Mais especificamente queria reproduzir a estratégia FAB4 no Profit, ou seja, ele varrer as ações onde o mercado está acima da média de 20, a média 20 acima da 200 e também o preço estar acima do prior cote de fechamento....

Mas para uma coisa tão simples assim o profit parece muito limitado e visualmente varrer as ações é uma ação quase que impossível... Alguem consegue me dar algum conselho? 

Valeu

**Comment by jozephbrasil** [comment]
Olá Oliver. Aqui não seria o melhor local pra tratar disso. Sugiro você fazer essa pergunta no grupo do Facebook: https://www.facebook.com/groups/estrategiasbacktestsprofitchart/. Mas é possível fazer o que você está dizendo sim, usando o Screening. Eu só não me lembro o período que o screening funciona (acho que é diário). Bom, vou fechar esse issue já que não é o foco aqui.
