### ISSUE TITLE
Screening + Desvio de uma média

### ISSUE THREAD

**Issue by luiztosi** [b2tradingclub/profitchart-estrategias#12]
Pessoal, estou tentando desenvolver algo simples e gostaria de contar com a ajuda de voces. 

Eu quero usar um filtro no Screening do Profitchart, onde eu coloco um % de desvio do preço em relação a média de 21.

Existe um indicador que é exportado na DDE do Vlad chamado AFASTAMENTO MEDIO, que seria basicamente aquele ou mesmo um outro chamado OSCILADOR DE PREÇOS.

A minha idéia seria ver os ativos que estão a X% distante da média móvel para encontrar bons pullbacks.

Alguem conseguiria me ajudar nisso?  Meu problema nem é tanto desenvolver a logica disso, mas não faço ideia de como retornar isso a uma variável e poder usar no screening.

Obrigado

**Comment by drecchia** [comment]
O screeening vai ler a variavel do Plot, basta retornar como se fosse criar um indicador. PS: use apenas 1 plot.

**Comment by luiztosi** [comment]
> O screeening vai ler a variavel do Plot, basta retornar como se fosse criar um indicador. PS: use apenas 1 plot.

Cara, obrigado pela ajuda... voce se importaria de me dar um exemplo de como poderia ser?

Eu conheco o paintbar, mas nunca trabalhei com o Plot

Obrigado

**Comment by drecchia** [comment]
https://github.com/b2tradingclub/profitchart-estrategias/blob/master/PhiCube/PhiCube_PCPV/PhiCube_PC_B2.src

**Comment by luiztosi** [comment]
> https://github.com/b2tradingclub/profitchart-estrategias/blob/master/PhiCube/PhiCube_PCPV/PhiCube_PC_B2.src

Valeu... me tira uma ultima duvida por favor?

begin
  Plot(Fechamento - Media(20,close));
end;

Eu fiz isso, até ai funciona perfeito, mas matematicamente como posso transformar isso em percentual?

Do tipo A média móvel está a X porcento do preço ? por que ai eu consigo utilizar universalmente.

seria 100-(PREÇO/MÉDIA) ?

**Comment by drecchia** [comment]
O coeficiente de variação (CV) é definido como a razão do desvio padrão σ pela média μ:

    cv = σ / μ

logo, traduzindo para sua realidade:

cv = (Fechamento - Media(20,close)) / 20

Não é percentual, mas deve ser comum entre os ativos.
