### ISSUE TITLE
Codigo mais complicado que o necessario, O Coidgo  abaixo faz a mesma coisa mais simples

### ISSUE THREAD

**Issue by 3DgeekStore** [b2tradingclub/profitchart-estrategias#5]
input
  len(8);
  source(CLOSE);
  exponencial(true);

var
  value : Float;
  last : Float;
  
begin

  value := 0.0;

  if ( last = 0.0 ) then
  begin
    if ( exponencial ) then
      value := MediaExp(len, source)    
    else
      value := Media(len, source);    
  end
    else
    value := ( last * ( len - 1 ) + source ) / len;

  last := value;

  SetPlotWidth(1, 3);
  SetPlotColor(1, clRed);  
  Plot(value);
end;

**Comment by jozephbrasil** [comment]
Olá. Você está se referindo a qual indicador?

**Comment by drecchia** [comment]
SMMA
