### ISSUE TITLE
Mais simples ainda

### ISSUE THREAD

**Issue by 3DgeekStore** [b2tradingclub/profitchart-estrategias#6]
// Contribuição do Danilo Recchia
input
  len(8);
  source(CLOSE);
  exponencial(true);

var
  value : Float;
  last : Float;
  
begin

  value := 0.0;

  if ( last = 0.0 ) then
    if ( exponencial ) then
       value := MediaExp(len, source)    
    else
      value := Media(len, source)    
  else
    value := ( last * ( len - 1 ) + source ) / len;

  last := value;
  SetPlotWidth(1, 3);
  SetPlotColor(1, clRed);  
  Plot(value);
end;

**Comment by drecchia** [comment]
(SMMA) Amigao, voce so retirou o begin e o end dos blocos IFs, se quer contribuir que seja com algo que realmente agregue. Layout de codigo é algo pessoal, eu prefiro declarar explicitamente meus codigos. Obrigado.
