### ISSUE TITLE
O codigo é interpretado, quando menos carecteres mais rapido ele roda

### ISSUE THREAD

**Issue by 3DgeekStore** [b2tradingclub/profitchart-estrategias#9]
Não é frescura "Amigão"  é Velocidade, Quanto mais sabemos,  mais sabermos que não sabemos

**Comment by drecchia** [comment]
Quem faz a otimizacao é o compilador, independente de vc declara uma variavel de nome "x" ou "abcdef".  Isso deixou de ser parametro a algum tempo.  Mas ok, segue o jogo.
